//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.05 at 04:40:10 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://com.springbootsoap/products", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package springbootsoap.com.products;
